[2023-10-22T17:14:54.320+0800] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sneakylol_listen_dag.listen_to_channel_task scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-10-22T17:14:54.325+0800] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sneakylol_listen_dag.listen_to_channel_task scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-10-22T17:14:54.325+0800] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-22T17:14:54.332+0800] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): listen_to_channel_task> on 2023-10-01 00:00:00+00:00
[2023-10-22T17:14:54.336+0800] {standard_task_runner.py:57} INFO - Started process 101 to run task
[2023-10-22T17:14:54.341+0800] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sneakylol_listen_dag', 'listen_to_channel_task', 'scheduled__2023-10-01T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/dags_generator.py', '--cfg-path', '/tmp/tmpj8xr9npa']
[2023-10-22T17:14:54.342+0800] {standard_task_runner.py:85} INFO - Job 48: Subtask listen_to_channel_task
[2023-10-22T17:14:54.380+0800] {task_command.py:415} INFO - Running <TaskInstance: sneakylol_listen_dag.listen_to_channel_task scheduled__2023-10-01T00:00:00+00:00 [running]> on host 7781ba1548ef
[2023-10-22T17:14:54.425+0800] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sneakylol_listen_dag' AIRFLOW_CTX_TASK_ID='listen_to_channel_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-01T00:00:00+00:00'
[2023-10-22T17:14:54.796+0800] {logging_mixin.py:151} INFO - getting 'startedAt' for sneakylol's live stream...
[2023-10-22T17:14:56.083+0800] {twitch_api_manager.py:69} INFO - {'id': '42948884155', 'user_id': '24538518', 'user_login': 'sneakylol', 'user_name': 'sneakylol', 'game_id': '21779', 'game_name': 'League of Legends', 'type': 'live', 'title': 'worlds swiss day 4 with da boys #Worlds2023', 'viewer_count': 5266, 'started_at': '2023-10-22T11:29:56+08:00', 'language': 'en', 'thumbnail_url': 'https://static-cdn.jtvnw.net/previews-ttv/live_user_sneakylol-{width}x{height}.jpg', 'tag_ids': [], 'tags': ['English'], 'is_mature': False}
[2023-10-22T17:14:56.089+0800] {logging_mixin.py:151} INFO - sneakylol's live stream started at 2023-10-22T11:29:56+08:00
[2023-10-22T17:14:56.090+0800] {logging_mixin.py:151} INFO - ircbot_manager: trying to insert 'start_tracking_livestream' task record into taskRecords...
[2023-10-22T17:14:56.715+0800] {logging_mixin.py:151} INFO - successfully insert task records.
[2023-10-22T17:14:56.716+0800] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_generator.py", line 55, in listen_to_channel_task
    listener.listen_to_chatroom()
  File "/opt/airflow/plugins/managers/ircbot_manager.py", line 172, in listen_to_chatroom
    self.connect_chatroom()
  File "/opt/airflow/plugins/managers/ircbot_manager.py", line 65, in connect_chatroom
    handlers=[logging.FileHandler(os.getcwd() + f'/dags/chat_logs/{self.started_at}_{self.channel}.log',
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/chat_logs/2023-10-22T11:29:56+08:00_sneakylol.log'
[2023-10-22T17:14:56.731+0800] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=sneakylol_listen_dag, task_id=listen_to_channel_task, execution_date=20231001T000000, start_date=20231022T091454, end_date=20231022T091456
[2023-10-22T17:14:56.741+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 48 for task listen_to_channel_task ([Errno 2] No such file or directory: '/opt/airflow/dags/chat_logs/2023-10-22T11:29:56+08:00_sneakylol.log'; 101)
[2023-10-22T17:14:56.769+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T17:14:56.782+0800] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
