[2023-10-22T17:15:11.407+0800] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trick2g_listen_dag.listen_to_channel_task manual__2023-10-22T09:14:39.798877+00:00 [queued]>
[2023-10-22T17:15:11.410+0800] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trick2g_listen_dag.listen_to_channel_task manual__2023-10-22T09:14:39.798877+00:00 [queued]>
[2023-10-22T17:15:11.410+0800] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-22T17:15:11.416+0800] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): listen_to_channel_task> on 2023-10-22 09:14:39.798877+00:00
[2023-10-22T17:15:11.419+0800] {standard_task_runner.py:57} INFO - Started process 132 to run task
[2023-10-22T17:15:11.423+0800] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'trick2g_listen_dag', 'listen_to_channel_task', 'manual__2023-10-22T09:14:39.798877+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/dags_generator.py', '--cfg-path', '/tmp/tmpq5xq5x06']
[2023-10-22T17:15:11.424+0800] {standard_task_runner.py:85} INFO - Job 51: Subtask listen_to_channel_task
[2023-10-22T17:15:11.454+0800] {task_command.py:415} INFO - Running <TaskInstance: trick2g_listen_dag.listen_to_channel_task manual__2023-10-22T09:14:39.798877+00:00 [running]> on host 7781ba1548ef
[2023-10-22T17:15:11.498+0800] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trick2g_listen_dag' AIRFLOW_CTX_TASK_ID='listen_to_channel_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T09:14:39.798877+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T09:14:39.798877+00:00'
[2023-10-22T17:15:11.833+0800] {logging_mixin.py:151} INFO - getting 'startedAt' for trick2g's live stream...
[2023-10-22T17:15:13.169+0800] {twitch_api_manager.py:69} INFO - {'id': '41960111417', 'user_id': '28036688', 'user_login': 'trick2g', 'user_name': 'Trick2g', 'game_id': '21779', 'game_name': 'League of Legends', 'type': 'live', 'title': 'FIRSTSTRIKE/CRIT UDYR IS BACK!! HULL BREAKER NEFTS RIP????!!!!???!!!', 'viewer_count': 1222, 'started_at': '2023-10-22T08:10:54+08:00', 'language': 'en', 'thumbnail_url': 'https://static-cdn.jtvnw.net/previews-ttv/live_user_trick2g-{width}x{height}.jpg', 'tag_ids': [], 'tags': ['LoL', 'Toplane', 'Volibear', 'English', 'Dad', 'bald', 'LoudAF'], 'is_mature': True}
[2023-10-22T17:15:13.174+0800] {logging_mixin.py:151} INFO - trick2g's live stream started at 2023-10-22T08:10:54+08:00
[2023-10-22T17:15:13.174+0800] {logging_mixin.py:151} INFO - ircbot_manager: trying to insert 'start_tracking_livestream' task record into taskRecords...
[2023-10-22T17:15:13.782+0800] {logging_mixin.py:151} INFO - successfully insert task records.
[2023-10-22T17:15:13.785+0800] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_generator.py", line 55, in listen_to_channel_task
    listener.listen_to_chatroom()
  File "/opt/airflow/plugins/managers/ircbot_manager.py", line 172, in listen_to_chatroom
    self.connect_chatroom()
  File "/opt/airflow/plugins/managers/ircbot_manager.py", line 65, in connect_chatroom
    handlers=[logging.FileHandler(os.getcwd() + f'/dags/chat_logs/{self.started_at}_{self.channel}.log',
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/chat_logs/2023-10-22T08:10:54+08:00_trick2g.log'
[2023-10-22T17:15:13.810+0800] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=trick2g_listen_dag, task_id=listen_to_channel_task, execution_date=20231022T091439, start_date=20231022T091511, end_date=20231022T091513
[2023-10-22T17:15:13.824+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 51 for task listen_to_channel_task ([Errno 2] No such file or directory: '/opt/airflow/dags/chat_logs/2023-10-22T08:10:54+08:00_trick2g.log'; 132)
[2023-10-22T17:15:13.862+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T17:15:13.879+0800] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
